module.exports = [
    'create-companies-collection',
    'create-recommendations-collection',
    'calc-data-time',
    'create-workings-collection',
    'migration-2017-04-28-create-users-collection',
    'migration-2017-04-28-migrate-authors-to-users',
    'migration-2017-05-26-remove-null-estimated_hourly_wage-fields',
    'migration-2017-06-12-normalize-company-name',
    'create-likes-collection',
    'migrate-2017-04-23-create-experiences-collection',
    'create-experienceLikes-collection',
    'create-replyLikes-collection',
    'migration-2017-05-09-create-replies-collection',
    'create-companyKeywords-collection',
    'create-jobTitleKeywords-collection',
];
